class _BotCommands:
    def __init__(self):
        self.LeechCommand = 'leech3'
        self.gLeechCommand = 'gleech3'
        self.ExtractCommand = 'extract3'
        self.gExtractCommand = 'gextract3'
        self.ArchiveCommand = 'archive3'
        self.gArchiveCommand = 'garchive3'
        self.telegramfleechCommand = 'tleech3'
        self.telegramexleechCommand = 'tleechextract3'
        self.gcloneCommand = 'gclone3'
        self.YtdlCommand = 'ytdl3'
        self.gYtdlCommand = 'gytdl3'
        self.PytdlCommand = 'pytdl3'
        self.gPytdlCommand = 'pytdl3'        
        self.ToggleDocCommand = 'toggledoc3'
        self.ToggleVidCommand = 'togglevid3'
        self.SaveCommand = 'savethumb3'
        self.ClearCommand = 'clearthumb3'
        self.RenameCommand = 'rename3'
        self.StatusCommand = 'status3'
        self.SpeedCommand = 'speedtest3'
        self.HelpCommand = 'help3'
        self.LogCommand = 'log3'
        self.TsHelpCommand = 'tshelp3'

BotCommands = _BotCommands()
